package com.java.jdbc.dbutils;

import java.sql.SQLException;
import java.util.List;

import org.apache.commons.dbutils.BasicRowProcessor;
import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;

public class Test {

	@org.junit.Test
	public void testColumnListHandler() throws SQLException
	 {
	  QueryRunner runer = new QueryRunner();
	  String sql = "select * from box_user ";
	  List<BoxUser> list = (List<BoxUser>)runer.query(ConnectionUtils.getConnection(),sql,new BeanListHandler(BoxUser.class));
	  for(BoxUser name: list)
	  {
	   System.out.println(name.getUser_id());
	  }
	  runer = new QueryRunner();
	  ResultSetHandler<List<BoxUser>> h = new BeanListHandler(BoxUser.class, new BasicRowProcessor(new MyBeanProcessor(new HumpMatcher())));
	// Execute the SQL statement and return the results in a List of
	// Person objects generated by the BeanListHandler.
	List<BoxUser> persons = runer.query(ConnectionUtils.getConnection(),"SELECT * FROM box_user", h);
	for(BoxUser name: persons)
	  {
	   System.out.println(name.getUserNo());
	  }
	 }
}
