// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarInfoMsg.proto

package com.netty.protobuf;

public final class CarInfos {
  private CarInfos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CarOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessage
      implements CarOrBuilder {
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Car(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Car defaultInstance;
    public static Car getDefaultInstance() {
      return defaultInstance;
    }

    public Car getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.protobuf.CarInfos.internal_static_Car_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.protobuf.CarInfos.internal_static_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.protobuf.CarInfos.Car.class, com.netty.protobuf.CarInfos.Car.Builder.class);
    }

    public static com.google.protobuf.Parser<Car> PARSER =
        new com.google.protobuf.AbstractParser<Car>() {
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Car(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Car.CarModel}
     */
    public enum CarModel
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BENZ = 0;</code>
       */
      BENZ(0, 0),
      /**
       * <code>VOLKSWAGEN = 1;</code>
       */
      VOLKSWAGEN(1, 1),
      /**
       * <code>FORD = 2;</code>
       */
      FORD(2, 2),
      /**
       * <code>CHEVROLET = 3;</code>
       */
      CHEVROLET(3, 3),
      /**
       * <code>TOYOTA = 4;</code>
       */
      TOYOTA(4, 4),
      /**
       * <code>Peugeot = 5;</code>
       */
      Peugeot(5, 5),
      ;

      /**
       * <code>BENZ = 0;</code>
       */
      public static final int BENZ_VALUE = 0;
      /**
       * <code>VOLKSWAGEN = 1;</code>
       */
      public static final int VOLKSWAGEN_VALUE = 1;
      /**
       * <code>FORD = 2;</code>
       */
      public static final int FORD_VALUE = 2;
      /**
       * <code>CHEVROLET = 3;</code>
       */
      public static final int CHEVROLET_VALUE = 3;
      /**
       * <code>TOYOTA = 4;</code>
       */
      public static final int TOYOTA_VALUE = 4;
      /**
       * <code>Peugeot = 5;</code>
       */
      public static final int Peugeot_VALUE = 5;


      public final int getNumber() { return value; }

      public static CarModel valueOf(int value) {
        switch (value) {
          case 0: return BENZ;
          case 1: return VOLKSWAGEN;
          case 2: return FORD;
          case 3: return CHEVROLET;
          case 4: return TOYOTA;
          case 5: return Peugeot;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CarModel>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CarModel>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CarModel>() {
              public CarModel findValueByNumber(int number) {
                return CarModel.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.netty.protobuf.CarInfos.Car.getDescriptor().getEnumTypes().get(0);
      }

      private static final CarModel[] VALUES = values();

      public static CarModel valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CarModel(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Car.CarModel)
    }

    /**
     * Protobuf enum {@code Car.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FEMALE = 0;</code>
       */
      FEMALE(0, 0),
      /**
       * <code>MALE = 1;</code>
       */
      MALE(1, 1),
      ;

      /**
       * <code>FEMALE = 0;</code>
       */
      public static final int FEMALE_VALUE = 0;
      /**
       * <code>MALE = 1;</code>
       */
      public static final int MALE_VALUE = 1;


      public final int getNumber() { return value; }

      public static Sex valueOf(int value) {
        switch (value) {
          case 0: return FEMALE;
          case 1: return MALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.netty.protobuf.CarInfos.Car.getDescriptor().getEnumTypes().get(1);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Sex(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Car.Sex)
    }

    public interface CarOwnerOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required .Car.Sex sex = 2 [default = MALE];
      /**
       * <code>required .Car.Sex sex = 2 [default = MALE];</code>
       */
      boolean hasSex();
      /**
       * <code>required .Car.Sex sex = 2 [default = MALE];</code>
       */
      com.netty.protobuf.CarInfos.Car.Sex getSex();

      // required int32 age = 3;
      /**
       * <code>required int32 age = 3;</code>
       */
      boolean hasAge();
      /**
       * <code>required int32 age = 3;</code>
       */
      int getAge();

      // required float height = 4;
      /**
       * <code>required float height = 4;</code>
       */
      boolean hasHeight();
      /**
       * <code>required float height = 4;</code>
       */
      float getHeight();
    }
    /**
     * Protobuf type {@code Car.CarOwner}
     */
    public static final class CarOwner extends
        com.google.protobuf.GeneratedMessage
        implements CarOwnerOrBuilder {
      // Use CarOwner.newBuilder() to construct.
      private CarOwner(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private CarOwner(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final CarOwner defaultInstance;
      public static CarOwner getDefaultInstance() {
        return defaultInstance;
      }

      public CarOwner getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private CarOwner(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.netty.protobuf.CarInfos.Car.Sex value = com.netty.protobuf.CarInfos.Car.Sex.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  sex_ = value;
                }
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                age_ = input.readInt32();
                break;
              }
              case 37: {
                bitField0_ |= 0x00000008;
                height_ = input.readFloat();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.protobuf.CarInfos.internal_static_Car_CarOwner_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.protobuf.CarInfos.internal_static_Car_CarOwner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.protobuf.CarInfos.Car.CarOwner.class, com.netty.protobuf.CarInfos.Car.CarOwner.Builder.class);
      }

      public static com.google.protobuf.Parser<CarOwner> PARSER =
          new com.google.protobuf.AbstractParser<CarOwner>() {
        public CarOwner parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CarOwner(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CarOwner> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required .Car.Sex sex = 2 [default = MALE];
      public static final int SEX_FIELD_NUMBER = 2;
      private com.netty.protobuf.CarInfos.Car.Sex sex_;
      /**
       * <code>required .Car.Sex sex = 2 [default = MALE];</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Car.Sex sex = 2 [default = MALE];</code>
       */
      public com.netty.protobuf.CarInfos.Car.Sex getSex() {
        return sex_;
      }

      // required int32 age = 3;
      public static final int AGE_FIELD_NUMBER = 3;
      private int age_;
      /**
       * <code>required int32 age = 3;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }

      // required float height = 4;
      public static final int HEIGHT_FIELD_NUMBER = 4;
      private float height_;
      /**
       * <code>required float height = 4;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float height = 4;</code>
       */
      public float getHeight() {
        return height_;
      }

      private void initFields() {
        name_ = "";
        sex_ = com.netty.protobuf.CarInfos.Car.Sex.MALE;
        age_ = 0;
        height_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAge()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHeight()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, sex_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, age_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeFloat(4, height_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, sex_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, age_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, height_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.netty.protobuf.CarInfos.Car.CarOwner parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.netty.protobuf.CarInfos.Car.CarOwner parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.netty.protobuf.CarInfos.Car.CarOwner prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Car.CarOwner}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.netty.protobuf.CarInfos.Car.CarOwnerOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.netty.protobuf.CarInfos.internal_static_Car_CarOwner_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.netty.protobuf.CarInfos.internal_static_Car_CarOwner_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.netty.protobuf.CarInfos.Car.CarOwner.class, com.netty.protobuf.CarInfos.Car.CarOwner.Builder.class);
        }

        // Construct using com.netty.protobuf.CarInfos.Car.CarOwner.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          sex_ = com.netty.protobuf.CarInfos.Car.Sex.MALE;
          bitField0_ = (bitField0_ & ~0x00000002);
          age_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          height_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.netty.protobuf.CarInfos.internal_static_Car_CarOwner_descriptor;
        }

        public com.netty.protobuf.CarInfos.Car.CarOwner getDefaultInstanceForType() {
          return com.netty.protobuf.CarInfos.Car.CarOwner.getDefaultInstance();
        }

        public com.netty.protobuf.CarInfos.Car.CarOwner build() {
          com.netty.protobuf.CarInfos.Car.CarOwner result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.netty.protobuf.CarInfos.Car.CarOwner buildPartial() {
          com.netty.protobuf.CarInfos.Car.CarOwner result = new com.netty.protobuf.CarInfos.Car.CarOwner(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.sex_ = sex_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.age_ = age_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.height_ = height_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.netty.protobuf.CarInfos.Car.CarOwner) {
            return mergeFrom((com.netty.protobuf.CarInfos.Car.CarOwner)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.netty.protobuf.CarInfos.Car.CarOwner other) {
          if (other == com.netty.protobuf.CarInfos.Car.CarOwner.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasSex()) {
            setSex(other.getSex());
          }
          if (other.hasAge()) {
            setAge(other.getAge());
          }
          if (other.hasHeight()) {
            setHeight(other.getHeight());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasSex()) {
            
            return false;
          }
          if (!hasAge()) {
            
            return false;
          }
          if (!hasHeight()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.netty.protobuf.CarInfos.Car.CarOwner parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.netty.protobuf.CarInfos.Car.CarOwner) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required .Car.Sex sex = 2 [default = MALE];
        private com.netty.protobuf.CarInfos.Car.Sex sex_ = com.netty.protobuf.CarInfos.Car.Sex.MALE;
        /**
         * <code>required .Car.Sex sex = 2 [default = MALE];</code>
         */
        public boolean hasSex() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .Car.Sex sex = 2 [default = MALE];</code>
         */
        public com.netty.protobuf.CarInfos.Car.Sex getSex() {
          return sex_;
        }
        /**
         * <code>required .Car.Sex sex = 2 [default = MALE];</code>
         */
        public Builder setSex(com.netty.protobuf.CarInfos.Car.Sex value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          sex_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .Car.Sex sex = 2 [default = MALE];</code>
         */
        public Builder clearSex() {
          bitField0_ = (bitField0_ & ~0x00000002);
          sex_ = com.netty.protobuf.CarInfos.Car.Sex.MALE;
          onChanged();
          return this;
        }

        // required int32 age = 3;
        private int age_ ;
        /**
         * <code>required int32 age = 3;</code>
         */
        public boolean hasAge() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 age = 3;</code>
         */
        public int getAge() {
          return age_;
        }
        /**
         * <code>required int32 age = 3;</code>
         */
        public Builder setAge(int value) {
          bitField0_ |= 0x00000004;
          age_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 age = 3;</code>
         */
        public Builder clearAge() {
          bitField0_ = (bitField0_ & ~0x00000004);
          age_ = 0;
          onChanged();
          return this;
        }

        // required float height = 4;
        private float height_ ;
        /**
         * <code>required float height = 4;</code>
         */
        public boolean hasHeight() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required float height = 4;</code>
         */
        public float getHeight() {
          return height_;
        }
        /**
         * <code>required float height = 4;</code>
         */
        public Builder setHeight(float value) {
          bitField0_ |= 0x00000008;
          height_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float height = 4;</code>
         */
        public Builder clearHeight() {
          bitField0_ = (bitField0_ & ~0x00000008);
          height_ = 0F;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Car.CarOwner)
      }

      static {
        defaultInstance = new CarOwner(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Car.CarOwner)
    }

    public interface CarInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string carNumber = 11;
      /**
       * <code>required string carNumber = 11;</code>
       */
      boolean hasCarNumber();
      /**
       * <code>required string carNumber = 11;</code>
       */
      java.lang.String getCarNumber();
      /**
       * <code>required string carNumber = 11;</code>
       */
      com.google.protobuf.ByteString
          getCarNumberBytes();

      // required string brand = 12;
      /**
       * <code>required string brand = 12;</code>
       */
      boolean hasBrand();
      /**
       * <code>required string brand = 12;</code>
       */
      java.lang.String getBrand();
      /**
       * <code>required string brand = 12;</code>
       */
      com.google.protobuf.ByteString
          getBrandBytes();

      // required string color = 13;
      /**
       * <code>required string color = 13;</code>
       */
      boolean hasColor();
      /**
       * <code>required string color = 13;</code>
       */
      java.lang.String getColor();
      /**
       * <code>required string color = 13;</code>
       */
      com.google.protobuf.ByteString
          getColorBytes();

      // required .Car.CarModel model = 14 [default = FORD];
      /**
       * <code>required .Car.CarModel model = 14 [default = FORD];</code>
       */
      boolean hasModel();
      /**
       * <code>required .Car.CarModel model = 14 [default = FORD];</code>
       */
      com.netty.protobuf.CarInfos.Car.CarModel getModel();

      // required int64 price = 15;
      /**
       * <code>required int64 price = 15;</code>
       */
      boolean hasPrice();
      /**
       * <code>required int64 price = 15;</code>
       */
      long getPrice();

      // required .Car.CarOwner owner = 16;
      /**
       * <code>required .Car.CarOwner owner = 16;</code>
       */
      boolean hasOwner();
      /**
       * <code>required .Car.CarOwner owner = 16;</code>
       */
      com.netty.protobuf.CarInfos.Car.CarOwner getOwner();
      /**
       * <code>required .Car.CarOwner owner = 16;</code>
       */
      com.netty.protobuf.CarInfos.Car.CarOwnerOrBuilder getOwnerOrBuilder();
    }
    /**
     * Protobuf type {@code Car.CarInfo}
     */
    public static final class CarInfo extends
        com.google.protobuf.GeneratedMessage
        implements CarInfoOrBuilder {
      // Use CarInfo.newBuilder() to construct.
      private CarInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private CarInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final CarInfo defaultInstance;
      public static CarInfo getDefaultInstance() {
        return defaultInstance;
      }

      public CarInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private CarInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 90: {
                bitField0_ |= 0x00000001;
                carNumber_ = input.readBytes();
                break;
              }
              case 98: {
                bitField0_ |= 0x00000002;
                brand_ = input.readBytes();
                break;
              }
              case 106: {
                bitField0_ |= 0x00000004;
                color_ = input.readBytes();
                break;
              }
              case 112: {
                int rawValue = input.readEnum();
                com.netty.protobuf.CarInfos.Car.CarModel value = com.netty.protobuf.CarInfos.Car.CarModel.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(14, rawValue);
                } else {
                  bitField0_ |= 0x00000008;
                  model_ = value;
                }
                break;
              }
              case 120: {
                bitField0_ |= 0x00000010;
                price_ = input.readInt64();
                break;
              }
              case 130: {
                com.netty.protobuf.CarInfos.Car.CarOwner.Builder subBuilder = null;
                if (((bitField0_ & 0x00000020) == 0x00000020)) {
                  subBuilder = owner_.toBuilder();
                }
                owner_ = input.readMessage(com.netty.protobuf.CarInfos.Car.CarOwner.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(owner_);
                  owner_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000020;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.protobuf.CarInfos.internal_static_Car_CarInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.protobuf.CarInfos.internal_static_Car_CarInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.protobuf.CarInfos.Car.CarInfo.class, com.netty.protobuf.CarInfos.Car.CarInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<CarInfo> PARSER =
          new com.google.protobuf.AbstractParser<CarInfo>() {
        public CarInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CarInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CarInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string carNumber = 11;
      public static final int CARNUMBER_FIELD_NUMBER = 11;
      private java.lang.Object carNumber_;
      /**
       * <code>required string carNumber = 11;</code>
       */
      public boolean hasCarNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string carNumber = 11;</code>
       */
      public java.lang.String getCarNumber() {
        java.lang.Object ref = carNumber_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            carNumber_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string carNumber = 11;</code>
       */
      public com.google.protobuf.ByteString
          getCarNumberBytes() {
        java.lang.Object ref = carNumber_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          carNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string brand = 12;
      public static final int BRAND_FIELD_NUMBER = 12;
      private java.lang.Object brand_;
      /**
       * <code>required string brand = 12;</code>
       */
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string brand = 12;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brand_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string brand = 12;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string color = 13;
      public static final int COLOR_FIELD_NUMBER = 13;
      private java.lang.Object color_;
      /**
       * <code>required string color = 13;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string color = 13;</code>
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            color_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string color = 13;</code>
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required .Car.CarModel model = 14 [default = FORD];
      public static final int MODEL_FIELD_NUMBER = 14;
      private com.netty.protobuf.CarInfos.Car.CarModel model_;
      /**
       * <code>required .Car.CarModel model = 14 [default = FORD];</code>
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .Car.CarModel model = 14 [default = FORD];</code>
       */
      public com.netty.protobuf.CarInfos.Car.CarModel getModel() {
        return model_;
      }

      // required int64 price = 15;
      public static final int PRICE_FIELD_NUMBER = 15;
      private long price_;
      /**
       * <code>required int64 price = 15;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 price = 15;</code>
       */
      public long getPrice() {
        return price_;
      }

      // required .Car.CarOwner owner = 16;
      public static final int OWNER_FIELD_NUMBER = 16;
      private com.netty.protobuf.CarInfos.Car.CarOwner owner_;
      /**
       * <code>required .Car.CarOwner owner = 16;</code>
       */
      public boolean hasOwner() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .Car.CarOwner owner = 16;</code>
       */
      public com.netty.protobuf.CarInfos.Car.CarOwner getOwner() {
        return owner_;
      }
      /**
       * <code>required .Car.CarOwner owner = 16;</code>
       */
      public com.netty.protobuf.CarInfos.Car.CarOwnerOrBuilder getOwnerOrBuilder() {
        return owner_;
      }

      private void initFields() {
        carNumber_ = "";
        brand_ = "";
        color_ = "";
        model_ = com.netty.protobuf.CarInfos.Car.CarModel.FORD;
        price_ = 0L;
        owner_ = com.netty.protobuf.CarInfos.Car.CarOwner.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasCarNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasBrand()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasColor()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasModel()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPrice()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasOwner()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getOwner().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(11, getCarNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(12, getBrandBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(13, getColorBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeEnum(14, model_.getNumber());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt64(15, price_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeMessage(16, owner_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(11, getCarNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(12, getBrandBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(13, getColorBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(14, model_.getNumber());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(15, price_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(16, owner_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.netty.protobuf.CarInfos.Car.CarInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.netty.protobuf.CarInfos.Car.CarInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.netty.protobuf.CarInfos.Car.CarInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Car.CarInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.netty.protobuf.CarInfos.Car.CarInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.netty.protobuf.CarInfos.internal_static_Car_CarInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.netty.protobuf.CarInfos.internal_static_Car_CarInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.netty.protobuf.CarInfos.Car.CarInfo.class, com.netty.protobuf.CarInfos.Car.CarInfo.Builder.class);
        }

        // Construct using com.netty.protobuf.CarInfos.Car.CarInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getOwnerFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          carNumber_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          brand_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          color_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          model_ = com.netty.protobuf.CarInfos.Car.CarModel.FORD;
          bitField0_ = (bitField0_ & ~0x00000008);
          price_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000010);
          if (ownerBuilder_ == null) {
            owner_ = com.netty.protobuf.CarInfos.Car.CarOwner.getDefaultInstance();
          } else {
            ownerBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.netty.protobuf.CarInfos.internal_static_Car_CarInfo_descriptor;
        }

        public com.netty.protobuf.CarInfos.Car.CarInfo getDefaultInstanceForType() {
          return com.netty.protobuf.CarInfos.Car.CarInfo.getDefaultInstance();
        }

        public com.netty.protobuf.CarInfos.Car.CarInfo build() {
          com.netty.protobuf.CarInfos.Car.CarInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.netty.protobuf.CarInfos.Car.CarInfo buildPartial() {
          com.netty.protobuf.CarInfos.Car.CarInfo result = new com.netty.protobuf.CarInfos.Car.CarInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.carNumber_ = carNumber_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.brand_ = brand_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.color_ = color_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.model_ = model_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.price_ = price_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          if (ownerBuilder_ == null) {
            result.owner_ = owner_;
          } else {
            result.owner_ = ownerBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.netty.protobuf.CarInfos.Car.CarInfo) {
            return mergeFrom((com.netty.protobuf.CarInfos.Car.CarInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.netty.protobuf.CarInfos.Car.CarInfo other) {
          if (other == com.netty.protobuf.CarInfos.Car.CarInfo.getDefaultInstance()) return this;
          if (other.hasCarNumber()) {
            bitField0_ |= 0x00000001;
            carNumber_ = other.carNumber_;
            onChanged();
          }
          if (other.hasBrand()) {
            bitField0_ |= 0x00000002;
            brand_ = other.brand_;
            onChanged();
          }
          if (other.hasColor()) {
            bitField0_ |= 0x00000004;
            color_ = other.color_;
            onChanged();
          }
          if (other.hasModel()) {
            setModel(other.getModel());
          }
          if (other.hasPrice()) {
            setPrice(other.getPrice());
          }
          if (other.hasOwner()) {
            mergeOwner(other.getOwner());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasCarNumber()) {
            
            return false;
          }
          if (!hasBrand()) {
            
            return false;
          }
          if (!hasColor()) {
            
            return false;
          }
          if (!hasModel()) {
            
            return false;
          }
          if (!hasPrice()) {
            
            return false;
          }
          if (!hasOwner()) {
            
            return false;
          }
          if (!getOwner().isInitialized()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.netty.protobuf.CarInfos.Car.CarInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.netty.protobuf.CarInfos.Car.CarInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string carNumber = 11;
        private java.lang.Object carNumber_ = "";
        /**
         * <code>required string carNumber = 11;</code>
         */
        public boolean hasCarNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string carNumber = 11;</code>
         */
        public java.lang.String getCarNumber() {
          java.lang.Object ref = carNumber_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            carNumber_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string carNumber = 11;</code>
         */
        public com.google.protobuf.ByteString
            getCarNumberBytes() {
          java.lang.Object ref = carNumber_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            carNumber_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string carNumber = 11;</code>
         */
        public Builder setCarNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          carNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string carNumber = 11;</code>
         */
        public Builder clearCarNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          carNumber_ = getDefaultInstance().getCarNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required string carNumber = 11;</code>
         */
        public Builder setCarNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          carNumber_ = value;
          onChanged();
          return this;
        }

        // required string brand = 12;
        private java.lang.Object brand_ = "";
        /**
         * <code>required string brand = 12;</code>
         */
        public boolean hasBrand() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string brand = 12;</code>
         */
        public java.lang.String getBrand() {
          java.lang.Object ref = brand_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            brand_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string brand = 12;</code>
         */
        public com.google.protobuf.ByteString
            getBrandBytes() {
          java.lang.Object ref = brand_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            brand_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string brand = 12;</code>
         */
        public Builder setBrand(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          brand_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string brand = 12;</code>
         */
        public Builder clearBrand() {
          bitField0_ = (bitField0_ & ~0x00000002);
          brand_ = getDefaultInstance().getBrand();
          onChanged();
          return this;
        }
        /**
         * <code>required string brand = 12;</code>
         */
        public Builder setBrandBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          brand_ = value;
          onChanged();
          return this;
        }

        // required string color = 13;
        private java.lang.Object color_ = "";
        /**
         * <code>required string color = 13;</code>
         */
        public boolean hasColor() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string color = 13;</code>
         */
        public java.lang.String getColor() {
          java.lang.Object ref = color_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            color_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string color = 13;</code>
         */
        public com.google.protobuf.ByteString
            getColorBytes() {
          java.lang.Object ref = color_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            color_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string color = 13;</code>
         */
        public Builder setColor(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          color_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string color = 13;</code>
         */
        public Builder clearColor() {
          bitField0_ = (bitField0_ & ~0x00000004);
          color_ = getDefaultInstance().getColor();
          onChanged();
          return this;
        }
        /**
         * <code>required string color = 13;</code>
         */
        public Builder setColorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          color_ = value;
          onChanged();
          return this;
        }

        // required .Car.CarModel model = 14 [default = FORD];
        private com.netty.protobuf.CarInfos.Car.CarModel model_ = com.netty.protobuf.CarInfos.Car.CarModel.FORD;
        /**
         * <code>required .Car.CarModel model = 14 [default = FORD];</code>
         */
        public boolean hasModel() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required .Car.CarModel model = 14 [default = FORD];</code>
         */
        public com.netty.protobuf.CarInfos.Car.CarModel getModel() {
          return model_;
        }
        /**
         * <code>required .Car.CarModel model = 14 [default = FORD];</code>
         */
        public Builder setModel(com.netty.protobuf.CarInfos.Car.CarModel value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          model_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .Car.CarModel model = 14 [default = FORD];</code>
         */
        public Builder clearModel() {
          bitField0_ = (bitField0_ & ~0x00000008);
          model_ = com.netty.protobuf.CarInfos.Car.CarModel.FORD;
          onChanged();
          return this;
        }

        // required int64 price = 15;
        private long price_ ;
        /**
         * <code>required int64 price = 15;</code>
         */
        public boolean hasPrice() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required int64 price = 15;</code>
         */
        public long getPrice() {
          return price_;
        }
        /**
         * <code>required int64 price = 15;</code>
         */
        public Builder setPrice(long value) {
          bitField0_ |= 0x00000010;
          price_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 price = 15;</code>
         */
        public Builder clearPrice() {
          bitField0_ = (bitField0_ & ~0x00000010);
          price_ = 0L;
          onChanged();
          return this;
        }

        // required .Car.CarOwner owner = 16;
        private com.netty.protobuf.CarInfos.Car.CarOwner owner_ = com.netty.protobuf.CarInfos.Car.CarOwner.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.netty.protobuf.CarInfos.Car.CarOwner, com.netty.protobuf.CarInfos.Car.CarOwner.Builder, com.netty.protobuf.CarInfos.Car.CarOwnerOrBuilder> ownerBuilder_;
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        public boolean hasOwner() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        public com.netty.protobuf.CarInfos.Car.CarOwner getOwner() {
          if (ownerBuilder_ == null) {
            return owner_;
          } else {
            return ownerBuilder_.getMessage();
          }
        }
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        public Builder setOwner(com.netty.protobuf.CarInfos.Car.CarOwner value) {
          if (ownerBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            owner_ = value;
            onChanged();
          } else {
            ownerBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        public Builder setOwner(
            com.netty.protobuf.CarInfos.Car.CarOwner.Builder builderForValue) {
          if (ownerBuilder_ == null) {
            owner_ = builderForValue.build();
            onChanged();
          } else {
            ownerBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        public Builder mergeOwner(com.netty.protobuf.CarInfos.Car.CarOwner value) {
          if (ownerBuilder_ == null) {
            if (((bitField0_ & 0x00000020) == 0x00000020) &&
                owner_ != com.netty.protobuf.CarInfos.Car.CarOwner.getDefaultInstance()) {
              owner_ =
                com.netty.protobuf.CarInfos.Car.CarOwner.newBuilder(owner_).mergeFrom(value).buildPartial();
            } else {
              owner_ = value;
            }
            onChanged();
          } else {
            ownerBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        public Builder clearOwner() {
          if (ownerBuilder_ == null) {
            owner_ = com.netty.protobuf.CarInfos.Car.CarOwner.getDefaultInstance();
            onChanged();
          } else {
            ownerBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        public com.netty.protobuf.CarInfos.Car.CarOwner.Builder getOwnerBuilder() {
          bitField0_ |= 0x00000020;
          onChanged();
          return getOwnerFieldBuilder().getBuilder();
        }
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        public com.netty.protobuf.CarInfos.Car.CarOwnerOrBuilder getOwnerOrBuilder() {
          if (ownerBuilder_ != null) {
            return ownerBuilder_.getMessageOrBuilder();
          } else {
            return owner_;
          }
        }
        /**
         * <code>required .Car.CarOwner owner = 16;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.netty.protobuf.CarInfos.Car.CarOwner, com.netty.protobuf.CarInfos.Car.CarOwner.Builder, com.netty.protobuf.CarInfos.Car.CarOwnerOrBuilder> 
            getOwnerFieldBuilder() {
          if (ownerBuilder_ == null) {
            ownerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.netty.protobuf.CarInfos.Car.CarOwner, com.netty.protobuf.CarInfos.Car.CarOwner.Builder, com.netty.protobuf.CarInfos.Car.CarOwnerOrBuilder>(
                    owner_,
                    getParentForChildren(),
                    isClean());
            owner_ = null;
          }
          return ownerBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:Car.CarInfo)
      }

      static {
        defaultInstance = new CarInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Car.CarInfo)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netty.protobuf.CarInfos.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.protobuf.CarInfos.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.protobuf.CarInfos.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.protobuf.CarInfos.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.protobuf.CarInfos.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netty.protobuf.CarInfos.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netty.protobuf.CarInfos.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netty.protobuf.CarInfos.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netty.protobuf.CarInfos.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netty.protobuf.CarInfos.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netty.protobuf.CarInfos.Car prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.netty.protobuf.CarInfos.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.protobuf.CarInfos.internal_static_Car_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.protobuf.CarInfos.internal_static_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.protobuf.CarInfos.Car.class, com.netty.protobuf.CarInfos.Car.Builder.class);
      }

      // Construct using com.netty.protobuf.CarInfos.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.protobuf.CarInfos.internal_static_Car_descriptor;
      }

      public com.netty.protobuf.CarInfos.Car getDefaultInstanceForType() {
        return com.netty.protobuf.CarInfos.Car.getDefaultInstance();
      }

      public com.netty.protobuf.CarInfos.Car build() {
        com.netty.protobuf.CarInfos.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netty.protobuf.CarInfos.Car buildPartial() {
        com.netty.protobuf.CarInfos.Car result = new com.netty.protobuf.CarInfos.Car(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.protobuf.CarInfos.Car) {
          return mergeFrom((com.netty.protobuf.CarInfos.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.protobuf.CarInfos.Car other) {
        if (other == com.netty.protobuf.CarInfos.Car.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.protobuf.CarInfos.Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.protobuf.CarInfos.Car) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Car)
    }

    static {
      defaultInstance = new Car(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Car)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Car_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_CarOwner_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Car_CarOwner_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_CarInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Car_CarInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020CarInfoMsg.proto\"\334\002\n\003Car\032R\n\010CarOwner\022\014" +
      "\n\004name\030\001 \002(\t\022\033\n\003sex\030\002 \002(\0162\010.Car.Sex:\004MAL" +
      "E\022\013\n\003age\030\003 \002(\005\022\016\n\006height\030\004 \002(\002\032\213\001\n\007CarIn" +
      "fo\022\021\n\tcarNumber\030\013 \002(\t\022\r\n\005brand\030\014 \002(\t\022\r\n\005" +
      "color\030\r \002(\t\022\"\n\005model\030\016 \002(\0162\r.Car.CarMode" +
      "l:\004FORD\022\r\n\005price\030\017 \002(\003\022\034\n\005owner\030\020 \002(\0132\r." +
      "Car.CarOwner\"V\n\010CarModel\022\010\n\004BENZ\020\000\022\016\n\nVO" +
      "LKSWAGEN\020\001\022\010\n\004FORD\020\002\022\r\n\tCHEVROLET\020\003\022\n\n\006T" +
      "OYOTA\020\004\022\013\n\007Peugeot\020\005\"\033\n\003Sex\022\n\n\006FEMALE\020\000\022" +
      "\010\n\004MALE\020\001B\036\n\022com.netty.protobufB\010CarInfo",
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Car_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Car_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Car_descriptor,
              new java.lang.String[] { });
          internal_static_Car_CarOwner_descriptor =
            internal_static_Car_descriptor.getNestedTypes().get(0);
          internal_static_Car_CarOwner_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Car_CarOwner_descriptor,
              new java.lang.String[] { "Name", "Sex", "Age", "Height", });
          internal_static_Car_CarInfo_descriptor =
            internal_static_Car_descriptor.getNestedTypes().get(1);
          internal_static_Car_CarInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Car_CarInfo_descriptor,
              new java.lang.String[] { "CarNumber", "Brand", "Color", "Model", "Price", "Owner", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
