// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.netty4.erlproto;

public final class HeaderBuf {
  private HeaderBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 mtype = 1;
    /**
     * <code>required int32 mtype = 1;</code>
     *
     * <pre>
     *消息类型  
     * </pre>
     */
    boolean hasMtype();
    /**
     * <code>required int32 mtype = 1;</code>
     *
     * <pre>
     *消息类型  
     * </pre>
     */
    int getMtype();

    // optional int32 stype = 2;
    /**
     * <code>optional int32 stype = 2;</code>
     *
     * <pre>
     *业务类型  
     * </pre>
     */
    boolean hasStype();
    /**
     * <code>optional int32 stype = 2;</code>
     *
     * <pre>
     *业务类型  
     * </pre>
     */
    int getStype();

    // optional int32 sid = 3;
    /**
     * <code>optional int32 sid = 3;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    boolean hasSid();
    /**
     * <code>optional int32 sid = 3;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    int getSid();

    // optional .proto.Header.Map attr = 4;
    /**
     * <code>optional .proto.Header.Map attr = 4;</code>
     *
     * <pre>
     *附件
     * </pre>
     */
    boolean hasAttr();
    /**
     * <code>optional .proto.Header.Map attr = 4;</code>
     *
     * <pre>
     *附件
     * </pre>
     */
    com.netty4.erlproto.HeaderBuf.Header.Map getAttr();
    /**
     * <code>optional .proto.Header.Map attr = 4;</code>
     *
     * <pre>
     *附件
     * </pre>
     */
    com.netty4.erlproto.HeaderBuf.Header.MapOrBuilder getAttrOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Header}
   */
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Header(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }

    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mtype_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stype_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sid_ = input.readInt32();
              break;
            }
            case 34: {
              com.netty4.erlproto.HeaderBuf.Header.Map.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = attr_.toBuilder();
              }
              attr_ = input.readMessage(com.netty4.erlproto.HeaderBuf.Header.Map.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(attr_);
                attr_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty4.erlproto.HeaderBuf.Header.class, com.netty4.erlproto.HeaderBuf.Header.Builder.class);
    }

    public static com.google.protobuf.Parser<Header> PARSER =
        new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    public interface KeyValueOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string key = 1;
      /**
       * <code>required string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // required string value = 2;
      /**
       * <code>required string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>required string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code proto.Header.KeyValue}
     */
    public static final class KeyValue extends
        com.google.protobuf.GeneratedMessage
        implements KeyValueOrBuilder {
      // Use KeyValue.newBuilder() to construct.
      private KeyValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private KeyValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final KeyValue defaultInstance;
      public static KeyValue getDefaultInstance() {
        return defaultInstance;
      }

      public KeyValue getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private KeyValue(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_KeyValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_KeyValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty4.erlproto.HeaderBuf.Header.KeyValue.class, com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder.class);
      }

      public static com.google.protobuf.Parser<KeyValue> PARSER =
          new com.google.protobuf.AbstractParser<KeyValue>() {
        public KeyValue parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new KeyValue(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<KeyValue> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.KeyValue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.netty4.erlproto.HeaderBuf.Header.KeyValue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.Header.KeyValue}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_KeyValue_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_KeyValue_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.netty4.erlproto.HeaderBuf.Header.KeyValue.class, com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder.class);
        }

        // Construct using com.netty4.erlproto.HeaderBuf.Header.KeyValue.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_KeyValue_descriptor;
        }

        public com.netty4.erlproto.HeaderBuf.Header.KeyValue getDefaultInstanceForType() {
          return com.netty4.erlproto.HeaderBuf.Header.KeyValue.getDefaultInstance();
        }

        public com.netty4.erlproto.HeaderBuf.Header.KeyValue build() {
          com.netty4.erlproto.HeaderBuf.Header.KeyValue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.netty4.erlproto.HeaderBuf.Header.KeyValue buildPartial() {
          com.netty4.erlproto.HeaderBuf.Header.KeyValue result = new com.netty4.erlproto.HeaderBuf.Header.KeyValue(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.netty4.erlproto.HeaderBuf.Header.KeyValue) {
            return mergeFrom((com.netty4.erlproto.HeaderBuf.Header.KeyValue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.netty4.erlproto.HeaderBuf.Header.KeyValue other) {
          if (other == com.netty4.erlproto.HeaderBuf.Header.KeyValue.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.netty4.erlproto.HeaderBuf.Header.KeyValue parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.netty4.erlproto.HeaderBuf.Header.KeyValue) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string key = 1;
        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // required string value = 2;
        private java.lang.Object value_ = "";
        /**
         * <code>required string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:proto.Header.KeyValue)
      }

      static {
        defaultInstance = new KeyValue(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:proto.Header.KeyValue)
    }

    public interface MapOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // repeated .proto.Header.KeyValue items = 1;
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      java.util.List<com.netty4.erlproto.HeaderBuf.Header.KeyValue> 
          getItemsList();
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      com.netty4.erlproto.HeaderBuf.Header.KeyValue getItems(int index);
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      int getItemsCount();
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      java.util.List<? extends com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder> 
          getItemsOrBuilderList();
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder getItemsOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code proto.Header.Map}
     */
    public static final class Map extends
        com.google.protobuf.GeneratedMessage
        implements MapOrBuilder {
      // Use Map.newBuilder() to construct.
      private Map(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Map(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Map defaultInstance;
      public static Map getDefaultInstance() {
        return defaultInstance;
      }

      public Map getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Map(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  items_ = new java.util.ArrayList<com.netty4.erlproto.HeaderBuf.Header.KeyValue>();
                  mutable_bitField0_ |= 0x00000001;
                }
                items_.add(input.readMessage(com.netty4.erlproto.HeaderBuf.Header.KeyValue.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_Map_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_Map_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty4.erlproto.HeaderBuf.Header.Map.class, com.netty4.erlproto.HeaderBuf.Header.Map.Builder.class);
      }

      public static com.google.protobuf.Parser<Map> PARSER =
          new com.google.protobuf.AbstractParser<Map>() {
        public Map parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Map(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Map> getParserForType() {
        return PARSER;
      }

      // repeated .proto.Header.KeyValue items = 1;
      public static final int ITEMS_FIELD_NUMBER = 1;
      private java.util.List<com.netty4.erlproto.HeaderBuf.Header.KeyValue> items_;
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      public java.util.List<com.netty4.erlproto.HeaderBuf.Header.KeyValue> getItemsList() {
        return items_;
      }
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      public java.util.List<? extends com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder> 
          getItemsOrBuilderList() {
        return items_;
      }
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      public int getItemsCount() {
        return items_.size();
      }
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      public com.netty4.erlproto.HeaderBuf.Header.KeyValue getItems(int index) {
        return items_.get(index);
      }
      /**
       * <code>repeated .proto.Header.KeyValue items = 1;</code>
       */
      public com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder getItemsOrBuilder(
          int index) {
        return items_.get(index);
      }

      private void initFields() {
        items_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < items_.size(); i++) {
          output.writeMessage(1, items_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < items_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, items_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.netty4.erlproto.HeaderBuf.Header.Map parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.netty4.erlproto.HeaderBuf.Header.Map parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.netty4.erlproto.HeaderBuf.Header.Map prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.Header.Map}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.netty4.erlproto.HeaderBuf.Header.MapOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_Map_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_Map_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.netty4.erlproto.HeaderBuf.Header.Map.class, com.netty4.erlproto.HeaderBuf.Header.Map.Builder.class);
        }

        // Construct using com.netty4.erlproto.HeaderBuf.Header.Map.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getItemsFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (itemsBuilder_ == null) {
            items_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            itemsBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_Map_descriptor;
        }

        public com.netty4.erlproto.HeaderBuf.Header.Map getDefaultInstanceForType() {
          return com.netty4.erlproto.HeaderBuf.Header.Map.getDefaultInstance();
        }

        public com.netty4.erlproto.HeaderBuf.Header.Map build() {
          com.netty4.erlproto.HeaderBuf.Header.Map result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.netty4.erlproto.HeaderBuf.Header.Map buildPartial() {
          com.netty4.erlproto.HeaderBuf.Header.Map result = new com.netty4.erlproto.HeaderBuf.Header.Map(this);
          int from_bitField0_ = bitField0_;
          if (itemsBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              items_ = java.util.Collections.unmodifiableList(items_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.items_ = items_;
          } else {
            result.items_ = itemsBuilder_.build();
          }
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.netty4.erlproto.HeaderBuf.Header.Map) {
            return mergeFrom((com.netty4.erlproto.HeaderBuf.Header.Map)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.netty4.erlproto.HeaderBuf.Header.Map other) {
          if (other == com.netty4.erlproto.HeaderBuf.Header.Map.getDefaultInstance()) return this;
          if (itemsBuilder_ == null) {
            if (!other.items_.isEmpty()) {
              if (items_.isEmpty()) {
                items_ = other.items_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureItemsIsMutable();
                items_.addAll(other.items_);
              }
              onChanged();
            }
          } else {
            if (!other.items_.isEmpty()) {
              if (itemsBuilder_.isEmpty()) {
                itemsBuilder_.dispose();
                itemsBuilder_ = null;
                items_ = other.items_;
                bitField0_ = (bitField0_ & ~0x00000001);
                itemsBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getItemsFieldBuilder() : null;
              } else {
                itemsBuilder_.addAllMessages(other.items_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          for (int i = 0; i < getItemsCount(); i++) {
            if (!getItems(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.netty4.erlproto.HeaderBuf.Header.Map parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.netty4.erlproto.HeaderBuf.Header.Map) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // repeated .proto.Header.KeyValue items = 1;
        private java.util.List<com.netty4.erlproto.HeaderBuf.Header.KeyValue> items_ =
          java.util.Collections.emptyList();
        private void ensureItemsIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = new java.util.ArrayList<com.netty4.erlproto.HeaderBuf.Header.KeyValue>(items_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            com.netty4.erlproto.HeaderBuf.Header.KeyValue, com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder, com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder> itemsBuilder_;

        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public java.util.List<com.netty4.erlproto.HeaderBuf.Header.KeyValue> getItemsList() {
          if (itemsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(items_);
          } else {
            return itemsBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public int getItemsCount() {
          if (itemsBuilder_ == null) {
            return items_.size();
          } else {
            return itemsBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public com.netty4.erlproto.HeaderBuf.Header.KeyValue getItems(int index) {
          if (itemsBuilder_ == null) {
            return items_.get(index);
          } else {
            return itemsBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder setItems(
            int index, com.netty4.erlproto.HeaderBuf.Header.KeyValue value) {
          if (itemsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureItemsIsMutable();
            items_.set(index, value);
            onChanged();
          } else {
            itemsBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder setItems(
            int index, com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder builderForValue) {
          if (itemsBuilder_ == null) {
            ensureItemsIsMutable();
            items_.set(index, builderForValue.build());
            onChanged();
          } else {
            itemsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder addItems(com.netty4.erlproto.HeaderBuf.Header.KeyValue value) {
          if (itemsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureItemsIsMutable();
            items_.add(value);
            onChanged();
          } else {
            itemsBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder addItems(
            int index, com.netty4.erlproto.HeaderBuf.Header.KeyValue value) {
          if (itemsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureItemsIsMutable();
            items_.add(index, value);
            onChanged();
          } else {
            itemsBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder addItems(
            com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder builderForValue) {
          if (itemsBuilder_ == null) {
            ensureItemsIsMutable();
            items_.add(builderForValue.build());
            onChanged();
          } else {
            itemsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder addItems(
            int index, com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder builderForValue) {
          if (itemsBuilder_ == null) {
            ensureItemsIsMutable();
            items_.add(index, builderForValue.build());
            onChanged();
          } else {
            itemsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder addAllItems(
            java.lang.Iterable<? extends com.netty4.erlproto.HeaderBuf.Header.KeyValue> values) {
          if (itemsBuilder_ == null) {
            ensureItemsIsMutable();
            super.addAll(values, items_);
            onChanged();
          } else {
            itemsBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder clearItems() {
          if (itemsBuilder_ == null) {
            items_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            itemsBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public Builder removeItems(int index) {
          if (itemsBuilder_ == null) {
            ensureItemsIsMutable();
            items_.remove(index);
            onChanged();
          } else {
            itemsBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder getItemsBuilder(
            int index) {
          return getItemsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder getItemsOrBuilder(
            int index) {
          if (itemsBuilder_ == null) {
            return items_.get(index);  } else {
            return itemsBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public java.util.List<? extends com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder> 
             getItemsOrBuilderList() {
          if (itemsBuilder_ != null) {
            return itemsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(items_);
          }
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder addItemsBuilder() {
          return getItemsFieldBuilder().addBuilder(
              com.netty4.erlproto.HeaderBuf.Header.KeyValue.getDefaultInstance());
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder addItemsBuilder(
            int index) {
          return getItemsFieldBuilder().addBuilder(
              index, com.netty4.erlproto.HeaderBuf.Header.KeyValue.getDefaultInstance());
        }
        /**
         * <code>repeated .proto.Header.KeyValue items = 1;</code>
         */
        public java.util.List<com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder> 
             getItemsBuilderList() {
          return getItemsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            com.netty4.erlproto.HeaderBuf.Header.KeyValue, com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder, com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder> 
            getItemsFieldBuilder() {
          if (itemsBuilder_ == null) {
            itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                com.netty4.erlproto.HeaderBuf.Header.KeyValue, com.netty4.erlproto.HeaderBuf.Header.KeyValue.Builder, com.netty4.erlproto.HeaderBuf.Header.KeyValueOrBuilder>(
                    items_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            items_ = null;
          }
          return itemsBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:proto.Header.Map)
      }

      static {
        defaultInstance = new Map(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:proto.Header.Map)
    }

    private int bitField0_;
    // required int32 mtype = 1;
    public static final int MTYPE_FIELD_NUMBER = 1;
    private int mtype_;
    /**
     * <code>required int32 mtype = 1;</code>
     *
     * <pre>
     *消息类型  
     * </pre>
     */
    public boolean hasMtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 mtype = 1;</code>
     *
     * <pre>
     *消息类型  
     * </pre>
     */
    public int getMtype() {
      return mtype_;
    }

    // optional int32 stype = 2;
    public static final int STYPE_FIELD_NUMBER = 2;
    private int stype_;
    /**
     * <code>optional int32 stype = 2;</code>
     *
     * <pre>
     *业务类型  
     * </pre>
     */
    public boolean hasStype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 stype = 2;</code>
     *
     * <pre>
     *业务类型  
     * </pre>
     */
    public int getStype() {
      return stype_;
    }

    // optional int32 sid = 3;
    public static final int SID_FIELD_NUMBER = 3;
    private int sid_;
    /**
     * <code>optional int32 sid = 3;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    public boolean hasSid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 sid = 3;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    public int getSid() {
      return sid_;
    }

    // optional .proto.Header.Map attr = 4;
    public static final int ATTR_FIELD_NUMBER = 4;
    private com.netty4.erlproto.HeaderBuf.Header.Map attr_;
    /**
     * <code>optional .proto.Header.Map attr = 4;</code>
     *
     * <pre>
     *附件
     * </pre>
     */
    public boolean hasAttr() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .proto.Header.Map attr = 4;</code>
     *
     * <pre>
     *附件
     * </pre>
     */
    public com.netty4.erlproto.HeaderBuf.Header.Map getAttr() {
      return attr_;
    }
    /**
     * <code>optional .proto.Header.Map attr = 4;</code>
     *
     * <pre>
     *附件
     * </pre>
     */
    public com.netty4.erlproto.HeaderBuf.Header.MapOrBuilder getAttrOrBuilder() {
      return attr_;
    }

    private void initFields() {
      mtype_ = 0;
      stype_ = 0;
      sid_ = 0;
      attr_ = com.netty4.erlproto.HeaderBuf.Header.Map.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAttr()) {
        if (!getAttr().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, mtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, stype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, sid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, attr_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, attr_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netty4.erlproto.HeaderBuf.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netty4.erlproto.HeaderBuf.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netty4.erlproto.HeaderBuf.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.netty4.erlproto.HeaderBuf.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty4.erlproto.HeaderBuf.Header.class, com.netty4.erlproto.HeaderBuf.Header.Builder.class);
      }

      // Construct using com.netty4.erlproto.HeaderBuf.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttrFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        stype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (attrBuilder_ == null) {
          attr_ = com.netty4.erlproto.HeaderBuf.Header.Map.getDefaultInstance();
        } else {
          attrBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty4.erlproto.HeaderBuf.internal_static_proto_Header_descriptor;
      }

      public com.netty4.erlproto.HeaderBuf.Header getDefaultInstanceForType() {
        return com.netty4.erlproto.HeaderBuf.Header.getDefaultInstance();
      }

      public com.netty4.erlproto.HeaderBuf.Header build() {
        com.netty4.erlproto.HeaderBuf.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netty4.erlproto.HeaderBuf.Header buildPartial() {
        com.netty4.erlproto.HeaderBuf.Header result = new com.netty4.erlproto.HeaderBuf.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mtype_ = mtype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stype_ = stype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sid_ = sid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (attrBuilder_ == null) {
          result.attr_ = attr_;
        } else {
          result.attr_ = attrBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty4.erlproto.HeaderBuf.Header) {
          return mergeFrom((com.netty4.erlproto.HeaderBuf.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty4.erlproto.HeaderBuf.Header other) {
        if (other == com.netty4.erlproto.HeaderBuf.Header.getDefaultInstance()) return this;
        if (other.hasMtype()) {
          setMtype(other.getMtype());
        }
        if (other.hasStype()) {
          setStype(other.getStype());
        }
        if (other.hasSid()) {
          setSid(other.getSid());
        }
        if (other.hasAttr()) {
          mergeAttr(other.getAttr());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMtype()) {
          
          return false;
        }
        if (hasAttr()) {
          if (!getAttr().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty4.erlproto.HeaderBuf.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty4.erlproto.HeaderBuf.Header) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 mtype = 1;
      private int mtype_ ;
      /**
       * <code>required int32 mtype = 1;</code>
       *
       * <pre>
       *消息类型  
       * </pre>
       */
      public boolean hasMtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 mtype = 1;</code>
       *
       * <pre>
       *消息类型  
       * </pre>
       */
      public int getMtype() {
        return mtype_;
      }
      /**
       * <code>required int32 mtype = 1;</code>
       *
       * <pre>
       *消息类型  
       * </pre>
       */
      public Builder setMtype(int value) {
        bitField0_ |= 0x00000001;
        mtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mtype = 1;</code>
       *
       * <pre>
       *消息类型  
       * </pre>
       */
      public Builder clearMtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mtype_ = 0;
        onChanged();
        return this;
      }

      // optional int32 stype = 2;
      private int stype_ ;
      /**
       * <code>optional int32 stype = 2;</code>
       *
       * <pre>
       *业务类型  
       * </pre>
       */
      public boolean hasStype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 stype = 2;</code>
       *
       * <pre>
       *业务类型  
       * </pre>
       */
      public int getStype() {
        return stype_;
      }
      /**
       * <code>optional int32 stype = 2;</code>
       *
       * <pre>
       *业务类型  
       * </pre>
       */
      public Builder setStype(int value) {
        bitField0_ |= 0x00000002;
        stype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 stype = 2;</code>
       *
       * <pre>
       *业务类型  
       * </pre>
       */
      public Builder clearStype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stype_ = 0;
        onChanged();
        return this;
      }

      // optional int32 sid = 3;
      private int sid_ ;
      /**
       * <code>optional int32 sid = 3;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public boolean hasSid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 sid = 3;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <code>optional int32 sid = 3;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public Builder setSid(int value) {
        bitField0_ |= 0x00000004;
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sid = 3;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sid_ = 0;
        onChanged();
        return this;
      }

      // optional .proto.Header.Map attr = 4;
      private com.netty4.erlproto.HeaderBuf.Header.Map attr_ = com.netty4.erlproto.HeaderBuf.Header.Map.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.netty4.erlproto.HeaderBuf.Header.Map, com.netty4.erlproto.HeaderBuf.Header.Map.Builder, com.netty4.erlproto.HeaderBuf.Header.MapOrBuilder> attrBuilder_;
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      public boolean hasAttr() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      public com.netty4.erlproto.HeaderBuf.Header.Map getAttr() {
        if (attrBuilder_ == null) {
          return attr_;
        } else {
          return attrBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      public Builder setAttr(com.netty4.erlproto.HeaderBuf.Header.Map value) {
        if (attrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          attr_ = value;
          onChanged();
        } else {
          attrBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      public Builder setAttr(
          com.netty4.erlproto.HeaderBuf.Header.Map.Builder builderForValue) {
        if (attrBuilder_ == null) {
          attr_ = builderForValue.build();
          onChanged();
        } else {
          attrBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      public Builder mergeAttr(com.netty4.erlproto.HeaderBuf.Header.Map value) {
        if (attrBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              attr_ != com.netty4.erlproto.HeaderBuf.Header.Map.getDefaultInstance()) {
            attr_ =
              com.netty4.erlproto.HeaderBuf.Header.Map.newBuilder(attr_).mergeFrom(value).buildPartial();
          } else {
            attr_ = value;
          }
          onChanged();
        } else {
          attrBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      public Builder clearAttr() {
        if (attrBuilder_ == null) {
          attr_ = com.netty4.erlproto.HeaderBuf.Header.Map.getDefaultInstance();
          onChanged();
        } else {
          attrBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      public com.netty4.erlproto.HeaderBuf.Header.Map.Builder getAttrBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAttrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      public com.netty4.erlproto.HeaderBuf.Header.MapOrBuilder getAttrOrBuilder() {
        if (attrBuilder_ != null) {
          return attrBuilder_.getMessageOrBuilder();
        } else {
          return attr_;
        }
      }
      /**
       * <code>optional .proto.Header.Map attr = 4;</code>
       *
       * <pre>
       *附件
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.netty4.erlproto.HeaderBuf.Header.Map, com.netty4.erlproto.HeaderBuf.Header.Map.Builder, com.netty4.erlproto.HeaderBuf.Header.MapOrBuilder> 
          getAttrFieldBuilder() {
        if (attrBuilder_ == null) {
          attrBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.netty4.erlproto.HeaderBuf.Header.Map, com.netty4.erlproto.HeaderBuf.Header.Map.Builder, com.netty4.erlproto.HeaderBuf.Header.MapOrBuilder>(
                  attr_,
                  getParentForChildren(),
                  isClean());
          attr_ = null;
        }
        return attrBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.Header)
    }

    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.Header)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Header_KeyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Header_KeyValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Header_Map_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Header_Map_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014header.proto\022\005proto\"\252\001\n\006Header\022\r\n\005mtyp" +
      "e\030\001 \002(\005\022\r\n\005stype\030\002 \001(\005\022\013\n\003sid\030\003 \001(\005\022\037\n\004a" +
      "ttr\030\004 \001(\0132\021.proto.Header.Map\032&\n\010KeyValue" +
      "\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\032,\n\003Map\022%\n\005i" +
      "tems\030\001 \003(\0132\026.proto.Header.KeyValueB \n\023co" +
      "m.netty4.erlprotoB\tHeaderBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_Header_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Header_descriptor,
              new java.lang.String[] { "Mtype", "Stype", "Sid", "Attr", });
          internal_static_proto_Header_KeyValue_descriptor =
            internal_static_proto_Header_descriptor.getNestedTypes().get(0);
          internal_static_proto_Header_KeyValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Header_KeyValue_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_proto_Header_Map_descriptor =
            internal_static_proto_Header_descriptor.getNestedTypes().get(1);
          internal_static_proto_Header_Map_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Header_Map_descriptor,
              new java.lang.String[] { "Items", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
