
package com.java.jws.mySecond.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.java.jws.mySecond.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceDemo", targetNamespace = "http://mySecond.jws.java.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceDemo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://mySecond.jws.java.com/", className = "com.java.jws.mySecond.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://mySecond.jws.java.com/", className = "com.java.jws.mySecond.HelloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUser", targetNamespace = "http://mySecond.jws.java.com/", className = "com.java.jws.mySecond.ListUser")
    @ResponseWrapper(localName = "listUserResponse", targetNamespace = "http://mySecond.jws.java.com/", className = "com.java.jws.mySecond.ListUserResponse")
    public List<String> listUser();

}
