
package com.java.jws.mySecond.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiceDemo", targetNamespace = "http://server.hw.demo/", wsdlLocation = "http://localhost:9898/ServiceDemo?wsdl")
public class ServiceDemo_Service
    extends Service
{

    private final static URL SERVICEDEMO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.java.jws.mySecond.client.ServiceDemo_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.java.jws.mySecond.client.ServiceDemo_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9898/ServiceDemo?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9898/ServiceDemo?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICEDEMO_WSDL_LOCATION = url;
    }

    public ServiceDemo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceDemo_Service() {
        super(SERVICEDEMO_WSDL_LOCATION, new QName("http://server.hw.demo/", "ServiceDemo"));
    }

    /**
     * 
     * @return
     *     returns ServiceDemo
     */
    @WebEndpoint(name = "ServiceDemopott")
    public ServiceDemo getServiceDemopott() {
        return super.getPort(new QName("http://server.hw.demo/", "ServiceDemopott"), ServiceDemo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceDemo
     */
    @WebEndpoint(name = "ServiceDemopott")
    public ServiceDemo getServiceDemopott(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.hw.demo/", "ServiceDemopott"), ServiceDemo.class, features);
    }

}
